### ISSUE TITLE
Debugging data corruption

### ISSUE THREAD

**Issue by dfordivam** [haskell-haskey/haskey#72]
Hello again!

I am using haskey in my web application, and I have experienced data "corruption" a couple of times now.
This time I have a snapshot of the working data and data which throws this error (I think while decoding binary). The two snapshots are taken 1 hour apart, and I have a log of actions I did during that time.

    DecodeError \"could not decode TypeOverflow: not enough checksum bytes\"

So my question is
1. How to detect the problem at the earliest -
    I can send a mail to me saying "Data corrupted, debug/restore now"

2. Find the root cause of bug 
    what should be the strategy to debug and find the root cause?

    I did less than a dozen write transactions during this time. And they all look pretty simple, I do them all the time without a problem. I am not sure what can be the cause of the bug, can transactReadOnly also cause issues?

   What is the significance of this error? It looks like a problem with internals of the haskey..

**Comment by hverr** [comment]
Sorry for the long delay, see #73.

**To quickly address your points:**

1. Depends on the size of your database, some ideas:
  - Periodically read the whole database in a background thread
  - Read written data immediately after writing it.
  - Keep LRU of least recently touched keys, and read those after writing a new value

2. Some ideas
  - Modify Haskey by keeping track of all touched database pages during a write transaction. Read those back in after finishing a write transaction to check for corruption and see what goes wrong.

3. Can transactReadOnly cause issues?
  - As long as you are not modifying the data in this transaction (which should be impossible by design) it should not be posing any problems

4. What is the significance of this error?
  - It certainly looks like a problem with haskey's internals. However, we have extensive randomized tests which do lots of consecutive and even concurrent write transactions and read transactions where data corruption is not an issue, so it still could go both ways, i.e. either database internals, either your specific usage of the library.

**Some questions from me to you:**
1. Does this error always occur when doing these write transactions? Or does it look like it is non-deterministic?
2. (If it is deterministic) do you have a minimal code example which triggers this corruption?
3. Are you using the database from multiple OS processes?
4. Are you using the library in a non standard way?
5. Do you have a log of read/write transactions (reproducible) that generate the data corruption?

**Comment by dfordivam** [comment]
Does this error always occur when doing these write transactions? Or does it look like it is non-deterministic?

This is completely non-deterministic. It happened once, otherwise the application is working fine..

    (If it is deterministic) do you have a minimal code example which triggers this corruption?
NA

    Are you using the database from multiple OS processes?
No, but I think I made a mistake here as the same db can be opened via the same application from multiple threads.
I have different db for each user, but if same user does login multiple places, there is possibility of opening same db from multiple threads.

    Are you using the library in a non standard way?
I think the usage is standard, except for the above mentioned point.

    Do you have a log of read/write transactions (reproducible) that generate the data corruption?
I tried all the write transactions again (5 in number, all were from same code), and there was no corruption.

I think I will fix this issue in my code, ie keep a store of open handles in MVar and make sure the same db cannot be opened from multiple threads. Since this issue has happened once it could very well be due to this bug in usage.

I will update more after testing this...

**Comment by hverr** [comment]
>> Are you using the database from multiple OS processes?

>No, but I think I made a mistake here as the same db can be opened via the same application from multiple threads.
> I have different db for each user, but if same user does login multiple places, there is possibility of opening same db from multiple threads.

I am inclined to say this is the source of the corruption, note that a database **must not** be opened multiple times (unless you **only** have readers).

However, you can safely share an open [`ConcurrentDb`](https://hackage.haskell.org/package/haskey-0.2.0.1/docs/Database-Haskey-Alloc-Concurrent.html#t:ConcurrentDb) amongst multiple threads.

I'm guessing you are using [`openConcurrentDb`](https://hackage.haskell.org/package/haskey-0.2.0.1/docs/Database-Haskey-Alloc-Concurrent.html#v:openConcurrentDb) right? An idea might be to try to lock the database before opening it using [`lockConcurrentDb`](https://hackage.haskell.org/package/haskey-0.2.0.1/docs/Database-Haskey-Alloc-Concurrent.html#v:lockConcurrentDb) (see documentation on `lockConcurrentDb`)

**Comment by dfordivam** [comment]
I did not experience corruption again, so I assume this was the mistake causing it.

**Comment by hverr** [comment]
Awesome! Let me know if you're experiencing it again.
